// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAOiWG3k1yJesX2CqlyC38RvCQv784lKng',
    appId: '1:999965060134:web:96f346cd8ded7b8b060ae7',
    messagingSenderId: '999965060134',
    projectId: 'loginflutter-d0527',
    authDomain: 'loginflutter-d0527.firebaseapp.com',
    storageBucket: 'loginflutter-d0527.firebasestorage.app',
    measurementId: 'G-DNSR0TNP3D',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBfSydZoeOV1xMLlDb6C9I937Di-JvgbcA',
    appId: '1:999965060134:android:5cfd26703dd5631c060ae7',
    messagingSenderId: '999965060134',
    projectId: 'loginflutter-d0527',
    storageBucket: 'loginflutter-d0527.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAd_qjrqa7bk-pWc6wDXprL2HoOsH_kxM4',
    appId: '1:999965060134:ios:f6c0ef62949a402c060ae7',
    messagingSenderId: '999965060134',
    projectId: 'loginflutter-d0527',
    storageBucket: 'loginflutter-d0527.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );
}
